### ISSUE TITLE
object is not an instance of declaring class

### ISSUE THREAD

**Issue by maint623** [PikaMug/LocaleLib#26] opened 2023-03-25 09:56 UTC
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.pikamug.localelib.LocaleManager.toServerLocale(LocaleManager.java:463) ~[LocaleLib-3.2.jar:?]
        at kr.maint.customshop.ShopEvent.clickEvent(ShopEvent.java:115) ~[CustomShop-1.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-406]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3165) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
```java
String key = localeManager.queryMaterial(Material.LAPIS_LAZULI);
                                    String englishName = "";
                                    try {
                                        englishName = localeManager.toServerLocale(key);
                                    } catch (IllegalAccessException | InvocationTargetException err) {
                                        err.printStackTrace();
                                    }
                                    System.out.println(englishName);`
```
I used the basic example, but I get an error

**Comment by PikaMug** [comment] 2023-03-25 16:09
Are you getting a reference to LocaleManager or instantiating it yourself? In other words are you doing this...
```java
private LocaleManager localeManager;

@Override
public void onEnable() {
   LocaleLib localeLib = (LocaleLib) getServer().getPluginManager().getPlugin("LocaleLib");
   if (localeLib != null) { localeManager = localeLib.getLocaleManager(); }
}
```
...or this...
```java
private LocaleManager localeManager = new LocaleManager();
```
...?

**Comment by maint623** [comment] 2023-03-26 09:14
use
`private LocaleManager localeManager = new LocaleManager();`

**Comment by PikaMug** [comment] 2023-04-03 02:52
Sorry I haven't had time to look into this further. Perhaps @UltraGameCoder (whom added the method) could take a look?

**Comment by UltraGameCoder** [comment] 2023-04-04 12:26
I found the solution to this problem. I will make a PR when I have implemented it at home.

The issue is that the implementation of `toServerLocale` references a `Class` type inside `localeClazz` but the first argument of `trans.invoke(localeClazz, key)` needs to be an instance of the class referenced by `localeClazz`. So the instance has to be obtained through Bukkit's API and be parsed as the first argument instead.

**Comment by UltraGameCoder** [comment] 2023-04-04 17:50
It seems I cannot implement my solution the way I wanted as it would require me to use NMS which would lead to multiple modules to support different version of minecraft.

But I do have a amazing solution from old source code I wrote a long while back which should definetly still work.
It might even bring up new ideas to add upon this project. I will add a bare minimum solution to inspire you to implement it further in which way you like @PikaMug.

**Comment by UltraGameCoder** [comment] 2023-04-04 18:27
@PikaMug Seems like I cannot create a PR for this. So here are the details:

**Subject:** Improved implementation of the me.pikamug.localelib.LocaleManager#toServerLocale method.

Previously, the method `me.pikamug.localelib.LocaleManager#toServerLocale` was causing an `java.lang.IllegalArgumentException` because of an `object is not an instance of declaring class` issue.
This was because the `java.lang.reflect.Method#invoke` method was expecting the instance of Bukkit's `LocaleLanguage` class for its first parameter.
Since we won't be able to obtain this instance without NMS and creating modules for many minecraft versions.
I got the idea of looking up some code I wrote years back: Loading in the en_US.lang file stored inside each server jar.
This way we can have a copy of their translations and allow this project to expand to reach new heights such as supporting additional mappings or even other languages by saving these lang files to disk. (This is what my old source code would've done. But I had abandoned it a long time ago because I just didn't have the time on my own to manage it. But maybe this project can! So if you're interested, you may reach out to me.)

Also, since my new computer system hasn't been fully setup for Minecraft development anymore.
Please make sure this reimplementation of the me.pikamug.localelib.LocaleManager#toServerLocale works as intended.

**Changes:**

A new method that loads in the en_US.lang file from the server jar.
```java
public class LocaleKeys {
...
/**
     * Loads all the translation entries from the en_US.lang file into a Properties object.
     * @return A Properties object consisting of the english translations
     * @throws IOException if an error occurred when reading from the en_US.lang file
     */
    public static Properties loadTranslations() throws IOException {
        ClassLoader classLoader = JavaPlugin.class.getClassLoader();
        InputStream inputStream = classLoader.getResourceAsStream("assets/minecraft/lang/en_US.lang");
        Properties properties = new Properties();
        properties.load(inputStream);
        return properties;
    }
}
```

A new field consisting of the loaded translations upon startup.
And the `toServerLocale` method fetches the translation from the field by its key.
```java
public class LocaleManager {
...
    private Properties englishTranslations;

    public LocaleManager() {
...
    try {
            englishTranslations = LocaleKeys.loadTranslations();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Gets the display name of the specified material as it would appear in a Minecraft lang file.
     * 
     * @param key the raw key for the object name
     * @return the display name of the specified key within the server locale file
     */
    public String toServerLocale(final String key) {
        return englishTranslations.getProperty(key);
    }
```

**Comment by PikaMug** [comment] 2023-04-06 02:04
@UltraGameCoder Thanks so much for looking into this! What you've come up with seems perfectly fine given the alternative. I'm not certain that I'd want to see this project saving files disk (namely due to the legal implications of bundling Mojang assets), but who knows what the future holds.

When you said you cannot create a PR, did you mean that a barrier was encountered, or that you wouldn't mind if I commit some form of this code on your behalf?

**Comment by UltraGameCoder** [comment] 2023-04-06 05:44
Both, when I try to create the PR inside InteliJ, the following error comes up: 

> Can't create a new pull request: Push failed: remote: Permission to PikaMug/LocaleLib.git denied to UltraGameCoder. unable to access 'https://github.com/PikaMug/LocaleLib.git/': The requested URL returned error: 403

But yes, I get that I would not be able to push this normally, but shouldn't it allow me to push for a PR?
So, I tried moving it over to a feature branch. But same errror there. So I think the only way to submit Pull Requests is by sending the code inside an Issue.

Therefor, be free to create your own form of this code on my behalf.

**Comment by UltraGameCoder** [comment] 2023-04-06 06:08
One thing I haven't tried is to first fork the project push my code there are make a PR to your original project. But I can't try that now as I am heading towards my work. So I'll try this when I am back home.

**Comment by UltraGameCoder** [comment] 2023-04-06 19:01
I was able to submit a PR after syncing my old fork of this project and adding the code.

**Comment by maint623** [comment] 2023-04-10 15:34
inStream parameter is null
`java.lang.NullPointerException: inStream parameter is null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.util.Properties.load(Properties.java:407) ~[?:?]
        at kr.maint.intycore.Manager.LocaleLib.Locale_Keys.loadTranslations(Locale_Keys.java:16) ~[INTY-Core-0.1.jar:?]
        at kr.maint.intycore.Manager.LocaleLib.Locale_Manager.LocaleManager(Locale_Manager.java:435) ~[INTY-Core-0.1.jar:?]
        at kr.maint.intycore.Manager.LocaleLib.Locale_Manager.toServerLocale(Locale_Manager.java:442) ~[INTY-Core-0.1.jar:?]
        at kr.maint.intycore.CustomGui.Gui_Event.clickEvent(Gui_Event.java:111) ~[INTY-Core-0.1.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-406]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3165) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by UltraGameCoder** [comment] 2023-04-10 15:50
@maint623 Could you share the version of server jar you are using? Perhaps use /version ingame?
I think its not able to load the translations because the translations are located on a different path inside the server jar.

**Comment by maint623** [comment] 2023-04-10 15:54
I am using 1.19.3

**Comment by UltraGameCoder** [comment] 2023-04-10 15:56
@maint623 Yes, but it can be different between distributors. You are using Paper-1.19.3-448?

**Comment by PikaMug** [comment] 2023-04-10 21:34
@UltraGameCoder On older version(s), it is uppercase (checked with 1.8).

**Comment by PikaMug** [comment] 2023-04-11 02:46
Should all be the same path, bar the capitalization. Confirmed 1.10.2 is uppercase, 1.11+ is lowercase.

**Comment by maint623** [comment] 2023-04-11 13:32
lang file gives an error, but there is no problem with json, but null is returned.

**Comment by maint623** [comment] 2023-04-11 13:40
![image](https://user-images.githubusercontent.com/98867089/231179354-cf5e6a2e-8860-4607-8c84-118ae9a4701a.png)

**Comment by maint623** [comment] 2023-04-11 14:57
```public static JSONObject loadTranslations() throws IOException {
        ClassLoader classLoader = JavaPlugin.class.getClassLoader();
        InputStream inputStream = classLoader.getResourceAsStream("assets/minecraft/lang/ko_kr.json");
        JSONParser jsonParser = new JSONParser();
        JSONObject jsonObject;
        try {
            jsonObject = (JSONObject)jsonParser.parse(new InputStreamReader(inputStream, "UTF-8"));
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        System.out.println(jsonObject);
        return jsonObject;
    }```
found a way

**Comment by maint623** [comment] 2023-04-11 15:02
but i need ko_kr.json
ko_us.json does not exist

**Comment by UltraGameCoder** [comment] 2023-04-11 17:51
Server jars only come with the default English (en_us) language.
Other languages will have to be translated from the english yourself.

Resources are loaded relatively from the classloader's classpath.
These resources should be within the resources folder of your project.

So in terms of your situation, your ko_kr.json should be located at: src/main/resources/kr/maint/intycore/ko_kr.json

**Closed** 2023-04-12 14:27 UTC
